---
server:
  timezone: UTC
  locales:
    - encoding: UTF-8
      name: en_US
    - encoding: UTF-8
      name: ru_RU
    - encoding: UTF-8
      name: ru_UA
    - encoding: UTF-8
      name: uk_UA
  repositories:
    - http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm
    - http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
    - http://rpms.famillecollet.com/enterprise/remi-release-6.rpm
  enablerepo: "epel,rpmforge,remi"
  packages:
    - "@development"
    - htop-1.0.3-1.el6.rf
    - iotop-0.3.2-7.el6
    - vim-enhanced-7.4.629-5.el6
    - curl-7.19.7-46.el6
    - wget-1.12-5.el6_6.1
    - mc-4.7.0.2-3.el6
    - screen-4.0.3-18.el6
    - strace-4.8-10.el6
    - telnet-0.17-48.el6
    - python-httplib2-0.7.7-1.el6
    - libselinux-python-2.0.94-5.8.el6
    - redis-3.0.7-2.el6.remi

scl:
  repository: centos-release-SCL-6-5.el6.centos
  enablerepo: "scl"
  packages:
    - python27-1.1-16.el6.centos.alt
  enable:
    - python27

mysql:
  root_password: 'root'
  modes:
    - "STRICT_ALL_TABLES"
  repository: http://www.percona.com/downloads/percona-release/redhat/0.1-3/percona-release-0.1-3.noarch.rpm
  enablerepo: "percona-release-noarch,percona-release-x86_64"
  packages:
    - MySQL-python-1.2.3-0.3.c1.1.el6
    - Percona-Server-client-55-5.5.48-rel37.8.el6
    - Percona-Server-server-55-5.5.48-rel37.8.el6
    - percona-toolkit-2.2.17-1

php:
  enablerepo: "remi,remi-php56"
  packages:
    - php-5.6.19-1.el6.remi
    - php-bcmath-5.6.19-1.el6.remi
    - php-cli-5.6.19-1.el6.remi
    - php-devel-5.6.19-1.el6.remi
    - php-fpm-5.6.19-1.el6.remi
    - php-gd-5.6.19-1.el6.remi
    - php-intl-5.6.19-1.el6.remi
    - php-mbstring-5.6.19-1.el6.remi
    - php-mcrypt-5.6.19-1.el6.remi
    - php-mysqlnd-5.6.19-1.el6.remi
    - php-opcache-5.6.19-1.el6.remi
    - php-pdo-5.6.19-1.el6.remi
    - php-xml-5.6.19-1.el6.remi
    - php-pear-1.10.1-4.el6.remi
    - php-pecl-memcached-2.2.0-3.el6.remi.5.6
    - php-pecl-redis-2.2.7-1.el6.remi.5.6
    - php-pecl-xdebug-2.3.3-1.el6.remi.5.6
    - php-pecl-xhprof-0.9.4-4.el6.remi.5.6

nginx:
  repository: http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm
  enablerepo: "nginx"
  packages:
    - nginx-1.8.1-1.el6.ngx

nodejs:
  url:  https://nodejs.org/dist/v5.8.0
  file: node-v5.8.0-linux-x64
  type: tar.xz
  npm:
    packages:
      - npm
      - grunt
