---
- name: install libselinux-python
  yum:
    name=libselinux-python
    state=present

- name: disable selinux
  selinux: state=disabled

- name: flush iptables
  shell: iptables -F && iptables -X && service iptables save
